version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=${R_AUTH_DB}'
      - 'POSTGRES_USER=${R_AUTH_USER}'
      - 'POSTGRES_PASSWORD=${R_AUTH_PASSWORD}'
    ports:
      - '5432:5432'

volumes:
  db:
    driver: local